[Settings]
Priority=Default
Properties=MyCustomProperty
 
[Default]
; Настройки MDT
OSInstall=Y
SkipBDDWelcome=YES
 
;Добавление в домен
JoinDomain=example.local
;MachineObjectOU=OU=Comps,DC=example,DC=local
DomainAdmin=USERNAME
DomainAdminDomain=example.local
DomainAdminPassword=PASSWORD
 
;Часовой пояс
SkipTimeZone=YES
TimeZoneName=Ekaterinburg Standard Time
 
;Региональные настройки
UILanguage = ru-RU
UserLocale = ru-RU
KeyboardLocale = ru-RU; en-US
SkipLocaleSelection= YES
SkipTimeZone = YES
 
;Пароль администратора
SkipAdminPassword=YES
AdminPassword=PASSWORD
 
;Захват образа
SkipCapture=NO
 
; Бэкап компьютера
SkipComputerBackup=NO
 
;Битлокер
SkipBitLocker=YES
 
;Ключ продукта
SkipProductKey=YES
